// Architecture diagram for MMRL++
// Generated by the multi-agent viz_arch.py (planner=gemini-3.1-flash-lite,
// renderer=CeTZ/fletcher; gemini-3-pro-image-preview path skipped because
// GEMINI_API_KEY was unset). Blueprint: fig_arch.blueprint.json.

#import "@preview/fletcher:0.5.1" as fletcher: node, edge

#figure(
  fletcher.diagram(
    node-stroke: 0.6pt,
    spacing: (12mm, 8mm),
    node-defocus: 0,

    // ===== Inputs =====
    node((0, 0.5), [Image\ $bold(x)$], shape: fletcher.shapes.rect, fill: rgb("#E0E0E0"), stroke: 0.6pt, name: <img_in>),
    node((0, 2.0), [Text\ "a photo of [c]"], shape: fletcher.shapes.rect, fill: rgb("#E0E0E0"), stroke: 0.6pt, name: <txt_in>),

    // ===== Frozen encoders =====
    node((1.4, 0.5), [Frozen Vision\ Encoder\ (ViT-B/16)\ #text(7pt)[layers 1-12]], shape: fletcher.shapes.rect, fill: rgb("#CFD8DC"), stroke: 0.6pt, name: <vit>),
    node((1.4, 2.0), [Frozen Text\ Encoder\ (Transformer)\ #text(7pt)[layers 1-12]], shape: fletcher.shapes.rect, fill: rgb("#CFD8DC"), stroke: 0.6pt, name: <txt_enc>),

    // ===== Representation tokens (centre) =====
    node((2.7, 1.25), [Representation\ Tokens $bold(R)_0$\ #text(7pt)[$n_r = 5$, $d_r = 512$]], shape: fletcher.shapes.rect, fill: rgb("#FFE0B2"), stroke: 0.6pt, name: <rep_tokens>),

    // ===== SRRA blocks =====
    node((4.0, 0.5), [*SRRA (Vision)*\ $f^"vis"_l(x) = (W_"base" + A_l B_l)x + b_l$\ #text(7pt)[~0.31M trainable]], shape: fletcher.shapes.rect, fill: rgb("#FFE0B2"), stroke: 0.6pt, name: <srra_vision>),
    node((4.0, 2.0), [*SRRA (Text)*\ $f^"txt"_l(x) = (W_"base" + A_l B_l)x + b_l$\ #text(7pt)[~0.31M trainable]], shape: fletcher.shapes.rect, fill: rgb("#FFE0B2"), stroke: 0.6pt, name: <srra_text>),

    // ===== PRC composer =====
    node((4.0, 1.25), [*PRC Composer*\ $bold(R)_l = beta bold(R)_(l-1) + (1-beta) bold(R)_0$\ #text(7pt)[$beta = 0.9$, layers 6-12]], shape: fletcher.shapes.rect, fill: rgb("#FFE0B2"), stroke: 0.6pt, name: <prc_composer>),

    // ===== Injection points =====
    node((5.3, 0.5), [Inject @ L 6-12], shape: fletcher.shapes.pill, fill: rgb("#FFF8E1"), stroke: 0.4pt, name: <inj_v>),
    node((5.3, 2.0), [Inject @ L 6-12], shape: fletcher.shapes.pill, fill: rgb("#FFF8E1"), stroke: 0.4pt, name: <inj_t>),

    // ===== Features =====
    node((6.6, 0.5), [$bold(v)_"rep"$,#h(0.3em) $bold(v)_"clip"$], shape: fletcher.shapes.rect, fill: rgb("#E0E0E0"), stroke: 0.6pt, name: <vis_feat>),
    node((6.6, 2.0), [$bold(t)_"rep"$,#h(0.3em) $bold(t)_"clip"$], shape: fletcher.shapes.rect, fill: rgb("#E0E0E0"), stroke: 0.6pt, name: <txt_feat>),

    // ===== Fusion =====
    node((8.0, 1.25), [*Weighted Fusion*\ $bold(z) = alpha bold(z)_"clip" + (1-alpha)bold(z)_"rep"$\ #text(7pt)[$alpha = 0.7$]], shape: fletcher.shapes.diamond, fill: rgb("#BBDEFB"), stroke: 0.6pt, name: <weighted_fusion>),

    // ===== Loss =====
    node((9.4, 1.25), [$cal(L)_"cls"$ + $lambda cal(L)_"reg"$], shape: fletcher.shapes.rect, fill: rgb("#FFCDD2"), stroke: 0.6pt, name: <loss>),

    // ===== Edges =====
    edge(<img_in>, <vit>, "->"),
    edge(<txt_in>, <txt_enc>, "->"),
    edge(<rep_tokens>, <srra_vision>, "->", label: text(7pt)[$bold(R)_l$]),
    edge(<rep_tokens>, <srra_text>, "->", label: text(7pt)[$bold(R)_l$]),
    edge(<rep_tokens>, <prc_composer>, "->", stroke: (paint: black, thickness: 0.6pt, dash: "dashed")),
    edge(<prc_composer>, <srra_vision>, "->", bend: 25deg, stroke: (paint: black, thickness: 0.6pt, dash: "dashed")),
    edge(<prc_composer>, <srra_text>, "->", bend: -25deg, stroke: (paint: black, thickness: 0.6pt, dash: "dashed")),
    edge(<srra_vision>, <inj_v>, "->"),
    edge(<srra_text>, <inj_t>, "->"),
    edge(<vit>, <inj_v>, "->"),
    edge(<txt_enc>, <inj_t>, "->"),
    edge(<inj_v>, <vis_feat>, "->"),
    edge(<inj_t>, <txt_feat>, "->"),
    edge(<vis_feat>, <weighted_fusion>, "->"),
    edge(<txt_feat>, <weighted_fusion>, "->"),
    edge(<weighted_fusion>, <loss>, "->"),
  ),
  caption: [
    MMRL++ architecture. Frozen CLIP encoders (gray) receive trainable
    representation tokens via per-layer Shared-Residual Representation
    Aligners (SRRA, amber) that share a base projection
    $W_"base"$ and add layer-specific rank-4 residuals $A_l B_l$. Tokens
    are progressively composed across layers 6--12 via the Progressive
    Representation Composition (PRC) module with weight $beta = 0.9$.
    The Weighted Fusion (blue) mixes original CLIP logits and
    representation-enhanced logits via $alpha = 0.7$, optimized with
    classification and cosine regularization losses.
  ],
) <fig_arch>

#v(0.4em)
#align(center)[
  #text(size: 7pt)[
    #stack(dir: ltr, spacing: 0.9em,
      [#box(fill: rgb("#CFD8DC"), width: 7pt, height: 7pt) #h(0.2em) Frozen (pretrained CLIP)],
      [#box(fill: rgb("#FFE0B2"), width: 7pt, height: 7pt) #h(0.2em) Trainable (SRRA + PRC, $0.78$M total)],
      [#box(fill: rgb("#BBDEFB"), width: 7pt, height: 7pt) #h(0.2em) Fusion],
      [#box(fill: rgb("#FFCDD2"), width: 7pt, height: 7pt) #h(0.2em) Loss],
    )
  ]
]
