= Related Work

== Vision-Language Models

Vision-language models have emerged as a powerful paradigm for learning transferable visual representations from natural language supervision. CLIP #cite(<radford2021clip>) pioneered this approach by training image and text encoders jointly on 400 million image-text pairs, achieving remarkable zero-shot transfer capabilities across diverse visual recognition tasks. The Vision Transformer (ViT) #cite(<dosovitskiy2020vit>) architecture, which applies the Transformer #cite(<vaswani2017attention>) mechanism to image patches, has become the dominant backbone for vision-language models due to its scalability and effectiveness. Building on these foundations, numerous works have explored architectural improvements #cite(<he2016deep>) and training strategies to enhance vision-language alignment.

== Prompt Learning for Vision-Language Models

Prompt learning has emerged as an efficient alternative to full fine-tuning for adapting pre-trained vision-language models to downstream tasks. CoOp #cite(<zhou2022coop>) introduced learnable continuous prompts in the text encoder, demonstrating that optimizing a small set of prompt tokens can achieve competitive performance with significantly fewer parameters than full fine-tuning. CoCoOp #cite(<zhou2022cocoop>) extended this approach with conditional prompts that adapt to each input instance, improving generalization to unseen classes. MaPLe #cite(<khattak2023maple>) further advanced multi-modal prompt learning by introducing learnable prompts in both vision and text branches, achieving state-of-the-art results on base-to-novel generalization and cross-dataset transfer.

Recent works have explored various prompt learning strategies. Distribution-aware prompt tuning #cite(<cho2023distribution>) incorporates distribution information to improve adaptation. Attribute-guided methods #cite(<tian2024argue>) leverage class-specific attributes for more targeted adaptation. Cluster-aware approaches #cite(<chen2026cluster>) ensemble multiple prompts for few-shot scenarios. Zhang et al. #cite(<zhang2026closer>) provide a comprehensive analysis of conditional prompt tuning mechanisms. However, these methods typically employ independent projection layers for each transformer layer, resulting in parameter redundancy without explicit gradient sharing across modalities and layers.

== Parameter-Efficient Fine-Tuning

Parameter-efficient fine-tuning (PEFT) techniques aim to adapt large pre-trained models with minimal trainable parameters. LoRA #cite(<hu2021lora>) introduced low-rank adaptation by decomposing weight updates into low-rank matrices, achieving competitive performance with a fraction of the parameters required for full fine-tuning. This approach has been widely adopted in language models and recently extended to vision-language models #cite(<huan2025fine>). Other PEFT methods include adapter layers #cite(<hamdi2026beft>), prefix tuning, and BitFit, each offering different trade-offs between parameter efficiency and performance #cite(<zheng2024llamafactory>).

While LoRA and related methods have demonstrated success in language models, their application to multi-modal vision-language adaptation presents unique challenges. Unlike language models where adaptation occurs in a single modality, vision-language models require coordinated adaptation across both visual and textual encoders while maintaining alignment with the pre-trained CLIP feature space. Our work addresses this challenge by designing SRRA specifically for multi-modal scenarios, enabling gradient sharing across both modalities and layers.

== Multi-Modal Representation Learning

Multi-modal representation learning focuses on learning joint representations that capture complementary information from multiple modalities. MMRL #cite(<guo2025mmrl>) introduced learnable representation tokens that are injected into both vision and text transformers, achieving strong performance on base-to-novel generalization and few-shot learning. However, MMRL employs independent projection layers for each transformer layer, limiting parameter efficiency and gradient sharing. Recent works have explored unsupervised fine-tuning #cite(<chen2026unsupervised>) and representation-based adaptation #cite(<sudarsanam2025representation>), but these approaches do not explicitly address parameter efficiency through shared-residual designs.

== Our Positioning

MMRL++ extends the multi-modal representation learning framework of MMRL with two key innovations that address parameter efficiency. First, our Shared-Residual Representation Aligner (SRRA) replaces independent per-layer projections with shared base weights and layer-specific low-rank residuals, substantially reducing trainable parameters while enabling gradient sharing across layers. Second, our Progressive Representation Composition (PRC) mechanism introduces inter-layer semantic flow through beta-weighted composition, enhancing intra-modal interaction beyond single-layer token injection. Unlike standard LoRA applications that adapt individual layers independently, SRRA is designed specifically for multi-modal scenarios where coordinated adaptation across vision and text encoders is critical. Our approach achieves superior parameter-performance trade-offs compared to both MMRL and MaPLe while maintaining or improving generalization across multiple evaluation settings.